server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    open-in-view: false
  freemarker:
    cache: false
    suffix: .ftl