server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    open-in-view: false
  freemarker:
    cache: false
    suffix: .ftl

disk-client:
  url: ${YANDEX_DISK_URL}
  token: ${YANDEX_DISK_TOKEN}
  path: "disk:/Приложения/blog/"