server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:h2:file:./data/test;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  freemarker:
    cache: false
    suffix: .ftl

disk-client:
  url: ${YANDEX_DISK_URL}
  token: ${YANDEX_DISK_TOKEN}
  path: "disk:/Приложения/blog/"